### ISSUE TITLE
[v1] Todo

### ISSUE THREAD

**Issue by prayash** [prayasht/bencrawford.media#1]
Blanket issue to track tasks that need to be done for v1.

- [x] A very basic static site scaffold w/ Gatsby.js
- [x] Homepage panels with dedicated transitions
- [x] Basic navigation system for desktop
- [ ] Hamburger menu navigation for mobile
- [ ] Slideshow components for Motion and Stills panels
- [ ] Central image for About panel
- [x] A rudimentary gallery page
- [x] A very basic about page with some content

Ops
- [x] Setup Netlify
- [x] Setup custom domain w/ Ben (we'll probably pair through this)
- [x] Get DNS info from Ben (can pair through this too)
- [x] Set up auto-deploys

Nice to haves:
- [ ] Pre-loading for the website (once content-size gets bulkier)
- [ ] Lazy-loaded gallery page (again, if needed)
- [x] Add some blogging functionality
- [ ] Nicer animations
